#!/bin/bash
# Get the current owner of the file
owner=$(stat -c '%U' hello)
# Check if the owner is guillaume
if [ "$owner" = "guillaume" ]; then
  # Change the owner to betty
  chown betty hello
  echo "Changed owner of hello to betty"
else
  echo "hello is not owned by guillaume"
fi

